Bug limite consumo energia
gspd-unesp/ispd pull request #3
Opened 2022-10-21 17:14 UTC by gustavo-1

2022-10-21 20:29 UTC, MathRPG requested changes
Remember to write commit descriptions in English, even if they're planned to be squashed. It helps make the repository consistent.

2022-10-21 20:29 UTC, MathRPG commented on src/ispd/gui/MainWindow.java
> +        //this.jFileChooser.setSelectedFile(this.configure.getLastFile());
Do not leave commented-out code in the repository.

2022-10-21 20:29 UTC, MathRPG commented on src/ispd/gui/UserConfigurationDialog.java
> +        String sResult ="";
Merge declaration and initialization in one line; make variable 'final' if applicable.

2022-10-21 20:29 UTC, MathRPG commented on src/ispd/gui/UserConfigurationDialog.java
> +        if (!this.userSet.contains(add) && !add.isEmpty() && !sResult.isEmpty() && !this.userSet.contains(sResult) ){
Overly-complex expression, extract this section of logic away into a method.

2022-11-06 20:32 UTC, MathRPG commented on src/ispd/gui/UserConfigurationDialog.java
> +        if (!add.isEmpty() && !this.userSet.contains(add)  && !sResult.isEmpty() && !this.userSet.contains(sResult) ){
Have you tested what happens when you cancel the input (i.e., close the prompt window)? Make sure it is working as intended.

2022-11-06 20:40 UTC, barrosoman commented on src/ispd/gui/UserConfigurationDialog.java
> +            JOptionPane.showMessageDialog(null, "Insert values corectly");
A typo in `corectly`, should be `correctly`.

2022-11-06 20:40 UTC, barrosoman commented on src/ispd/gui/UserConfigurationDialog.java
> +            final Double result = Double.parseDouble(sResult);
Test when the `sResult` is not a valid double, should be enclosed in a try/catch block.

2022-11-10 22:43 UTC, MathRPG requested changes
These review notes were talked about in person; but I'm documenting them here on github for consistency.

2022-12-04 19:37 UTC, MathRPG commented
Closed due to the GitLab migration

2022-12-04 19:37 UTC, closed without merging