fixed title
gspd-unesp/ispd pull request #8
Opened 2022-11-07 19:05 UTC by DaphLie

2022-11-08 09:24 UTC, ricardofares requested changes, later dismissed
We should aim to keep the text translations in iSPD, even if incomplete. To make any added/changed strings in your changes translatable, update the files in the package _src.ispd.idioma_;

2022-11-20 16:21 UTC, MathRPG commented
We should aim to keep the text translations in iSPD, even if incomplete. To make any added/changed strings in your changes translatable, update the files in the package `src.ispd.idioma`;

2022-12-02 16:24 UTC, MathRPG requested changes
Almost there, but there are extra spaces on the key for the English translation of the window title, which causes an exception to be thrown and the window to not open.

Make sure to test the application in both languages whenever you make a change in a translation.

2022-12-04 19:35 UTC, MathRPG approved these changes

2022-12-04 19:36 UTC, merged